version: '3'

services:
    meu-backend:
        image: openjdk:17-jdk-alpine3.14:1
        ports:
            - "8080:8080"
    postgres:
        image: postgres:15.2
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
